---
title: "MFA"
author: "Fatima"
date: "16/10/2022"
output: html_document
---

```{r}
library("rstudioapi") 
library("FactoMineR")
library("factoextra")
script_dir <- getSourceEditorContext()$path 
setwd(dirname(script_dir))

db <- read.table("Playstore-preprocessed.csv",header=T, sep=",")


db$Category<-as.factor(db$Category)
db$Minimum.Android<-as.factor(db$Minimum.Android)
db$Content.Rating<-as.factor(db$Content.Rating)
db$Ad.Supported<-as.logical(db$Ad.Supported)
db$In.App.Purchases<-as.logical(db$In.App.Purchases)


# db$Rating.Count<-log(db$Rating.Count+1)
# db$Size<-exp(db$Size)-1
# db$Installs<-exp(db$Installs)-1
```


```{r}

dd <- db[,c(9, 10, 3, 12, 2, 11, 4, 1, 6, 5, 7, 8)]
# View(dd)
res.mfa <- MFA(dd, 
          group = c(2, 3, 2, 3, 2), 
          type = c("s", "s", "s", "n", "n"),
          name.group = c("Antiquity", "Popularity", "App features", "Topic", "Monetization"),
          num.group.sup = c(1,4)
)

```


```{r}

eig.val <- get_eigenvalue(res.mfa)
eig.val
fviz_screeplot(res.mfa)
```

```{r}
# Contribution of each group for each dimension
fviz_contrib(res.mfa,  "group", axes = 1)
fviz_contrib(res.mfa, "group", axes = 2)
fviz_contrib(res.mfa, "group", axes = 3)
```
```{r}
# Contribution of each variable for each dimension
fviz_contrib(res.mfa,"quanti.var", axes = 1)
fviz_contrib(res.mfa,"quanti.var", axes = 2)
fviz_contrib(res.mfa,"quanti.var", axes = 3)

```


```{r}
#plot correlation between quantitative variables and dimensions
fviz_mfa_var(res.mfa, axes = c(1,2))
fviz_mfa_var(res.mfa, axes = c(1,3))
fviz_mfa_var(res.mfa, axes = c(2,3))

```


```{r}
plot(res.mfa,choix="group",partial="all", axes = c(1,2),)
plot(res.mfa,choix="group",partial="all", axes = c(1,3))
plot(res.mfa,choix="group",partial="all", axes = c(2,3))
```

```{r}
#comparison dimensions
fviz_mfa_axes(res.mfa, axes = c(1,2))
fviz_mfa_axes(res.mfa, axes = c(1,3))
fviz_mfa_axes(res.mfa, axes = c(2,3))
```

```{r}
fviz_mfa_ind(res.mfa, select.ind = list(contrib = 1000),
            col.ind = "cos2", 
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07", "#FC8E67"),
             repel = TRUE, axes = c(1,2))
fviz_mfa_ind(res.mfa, select.ind = list(contrib = 1000),
            col.ind = "cos2", 
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07", "#FC8E67"),
             repel = TRUE, axes = c(1,3))

fviz_mfa_ind(res.mfa, select.ind = list(contrib = 1000),
            col.ind = "cos2", 
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07", "#FC8E67"),
             repel = TRUE, axes = c(2,3))
```




```{r}
fviz_mfa_ind(res.mfa, partial = "all", axes = c(1,2))
fviz_mfa_ind(res.mfa, partial = "all", axes = c(1,3))
fviz_mfa_ind(res.mfa, partial = "all", axes = c(2,3))
```

