---
title: "PCA"
output: html_document
date: "2022-10-20"
---


```{r}
library("rstudioapi") 
script_dir <- getSourceEditorContext()$path 
setwd(dirname(script_dir))
db <- read.table("Playstore-preprocessed.csv",header=T, sep=",")
```


```{r}
db$Category<-as.factor(db$Category)
db$Minimum.Android<-as.factor(db$Minimum.Android)
db$Content.Rating<-as.factor(db$Content.Rating)
db$Ad.Supported<-as.factor(db$Ad.Supported)
db$In.App.Purchases<-as.factor(db$In.App.Purchases)

```


```{r}
numericalVariablesIndex <- which(sapply(db,is.numeric))
db_ori<-db
db<-db[,numericalVariablesIndex]
summary(db)
```

```{r}
dim(db) 
class(db)
str(db)
summary(db)
apply(X = db, MARGIN = 2, FUN = mean)
apply(X = db, MARGIN = 2, FUN = var) ##### Look at the high variance amongst features, so as it was studied, we need to scale our data for PCA.
##### Correlations, a quick view

Correlations <- cor(db)
print(Correlations)
corrplot::corrplot(Correlations) 
corrplot::corrplot(Correlations, method = "number",number.cex = 0.75)
```

```{r}
library("FactoMineR")
library("factoextra")
res.pca <- PCA(db, scale.unit = TRUE,graph = FALSE)


```

```{r}
print(res.pca)

eig.val <- get_eigenvalue(res.pca)
eig.val

fviz_eig(res.pca, addlabels = TRUE, ylim = c(0, 50))

var <- get_pca_var(res.pca)
var

# Contributions to the principal components
var$contrib

# Coordinates of variables
var$coord


fviz_pca_var(res.pca, col.var = "red")

var$cos2
library("corrplot")
corrplot(var$cos2[,1:5], is.corr=FALSE)

# Total cos2 of variables on Dim.1 and Dim.2
fviz_cos2(res.pca, choice = "var", axes = 1:2)
fviz_cos2(res.pca, choice = "var", axes = c(1,3))
fviz_cos2(res.pca, choice = "var", axes = 2:3)


# Color by cos2 values: quality on the factor map
fviz_pca_var(res.pca, col.var = "cos2",
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"), 
             repel = TRUE # Avoid text overlapping
             )

# Color by cos2 values: quality on the factor map
fviz_pca_var(res.pca, col.var = "cos2",axes = c(1,3),
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"), 
             repel = TRUE # Avoid text overlapping
             )

# Color by cos2 values: quality on the factor map
fviz_pca_var(res.pca, col.var = "cos2",axes = c(2,3),
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"), 
             repel = TRUE # Avoid text overlapping
             )

# Change the transparency by cos2 values
fviz_pca_var(res.pca, alpha.var = "cos2")


library("corrplot")
corrplot(var$contrib, is.corr=FALSE)
corrplot(var$cos2[, 1:3], is.corr=FALSE)

# Contributions of variables to PC1
fviz_contrib(res.pca, choice = "var", axes = 1, top = 10)
# Contributions of variables to PC2
fviz_contrib(res.pca, choice = "var", axes = 2, top = 10)
# Contributions of variables to PC3
fviz_contrib(res.pca, choice = "var", axes = 3, top = 10)

fviz_contrib(res.pca, choice = "var", axes = 1:2, top = 10)

#The most important (or, contributing) variables can be highlighted on the correlation plot as follow
fviz_pca_var(res.pca, col.var = "contrib",
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07")
             )

fviz_cos2(res.pca, choice = "ind",top=30)

# Total contribution on PC1 and PC2
fviz_contrib(res.pca, choice = "ind", axes = 1:2,top=20)



# Create a grouping variable using kmeans
# Create 3 groups of variables (centers = 3)
set.seed(123)
res.km <- kmeans(var$coord, centers = 3, nstart = 25)
grp <- as.factor(res.km$cluster)
# Color variables by groups
fviz_pca_var(res.pca, col.var = grp, axes = c(1,2),
             palette = c("#0073C2FF", "#EFC000FF", "#868686FF"),
             legend.title = "Cluster")

# Color variables by groups
fviz_pca_var(res.pca, col.var = grp, axes = c(2,3),
             palette = c("#0073C2FF", "#EFC000FF", "#868686FF"),
             legend.title = "Cluster")

# Color variables by groups
fviz_pca_var(res.pca, col.var = grp, axes = c(1,3),
             palette = c("#0073C2FF", "#EFC000FF", "#868686FF"),
             legend.title = "Cluster")

```

```{r}
res.desc <- dimdesc(res.pca, axes = 1:3, proba = 0.05)

# Description of dimension 1
res.desc$Dim.1

# Description of dimension 2
res.desc$Dim.2

# Description of dimension 3
res.desc$Dim.3
```


```{r}
ind <- get_pca_ind(res.pca)
ind

# Coordinates of individuals
head(ind$coord)
# Quality of individuals
head(ind$cos2)
  # Contributions of individuals
head(ind$contrib)

fviz_pca_ind(res.pca)

fviz_pca_ind(res.pca, col.ind = "cos2", axes = c(1,3),
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE # Avoid text overlapping (slow if many points)
             )

fviz_pca_ind(res.pca, col.ind = "cos2", axes = c(2,3),
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             select.ind = list(cos2 = 1000),
             repel = TRUE # Avoid text overlapping (slow if many points)
             )

fviz_pca_ind(res.pca, col.ind = "contrib",axes = c(1,2),
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07","#0073C2FF", "#868686FF"),
             repel = TRUE # Avoid text overlapping (slow if many points)
             )

fviz_contrib(res.pca, choice = "ind", axes = c(1,3),top=50)



```



```{r}
#Color by groups
fviz_pca_ind(res.pca,
             geom.ind = "point", # show points only (nbut not "text")
             col.ind = db_ori$Category, # color by groups
             palette = c("#00AFBB", "#E7B800", "#FC4E07","#0073C2FF", "#EFC000FF", "#868686FF"),
             addEllipses = FALSE, # Concentration ellipses
             legend.title = "Groups"
             )

  fviz_pca_ind(res.pca,
             geom.ind = "point", # show points only (nbut not "text"),
             select.ind = list(cos2 = 1000),
             col.ind = db_ori$Category, # color by groups
             palette = c("#00AFBB", "#E7B800", "#FC4E07","#0073C2FF", "#EFC000FF", "#868686FF"),
             addEllipses = FALSE, # Concentration ellipses
             legend.title = "Groups"
             )


fviz_pca_ind(res.pca,
             geom.ind = "point", # show points only (nbut not "text"),
             select.ind = list(cos2 = 1000),
             col.ind = db_ori$Content.Rating, # color by groups
             palette = c("#00AFBB", "#E7B800", "#FC4E07","#0073C2FF", "#EFC000FF", "#868686FF"),
             addEllipses = FALSE, # Concentration ellipses
             legend.title = "Groups"
             )


# Add confidence ellipses
fviz_pca_ind(res.pca, geom.ind = "point", col.ind = db_ori$Category, select.ind = list(cos2 = 1000),
             palette =  c("#00AFBB", "#E7B800", "#FC4E07","#0073C2FF", "#EFC000FF", "#868686FF"),
             addEllipses = TRUE, ellipse.type = "confidence",
             legend.title = "Groups"
             )

```

```{r}
#BIPLOTS OF VARIABLES AND INDIVIDUALS
fviz_pca_biplot(res.pca, repel = TRUE,axes = c(1,2),select.ind=list(cos2 = 1000),
                habillage=db_ori$Content.Rating,
                col.var = "#cc0000", # Variables color
                col.ind = "#6fa8dc"  # Individuals color
                )
fviz_pca_biplot(res.pca, repel = TRUE,axes = c(2,3),select.ind=list(cos2 = 1000),
                habillage=db_ori$Content.Rating,
                col.var = "#cc0000", # Variables color
                col.ind = "#6fa8dc"  # Individuals color
                )

fviz_pca_biplot(res.pca, repel = TRUE,axes = c(1,3),select.ind=list(cos2 = 1000),
                habillage=db_ori$Category,
                col.var = "#cc0000", # Variables color
                col.ind = "#6fa8dc"  # Individuals color
                )

```

```{r}
#ADDING SUMPLEMENTARY QUALITATIVE VARIABLE
fviz_pca_biplot(res.pca, select.ind = list(contrib = 50), 
               select.var = list(contrib = 5),
               ggtheme = theme_minimal())
numericalVariablesIndex <- which(sapply(db_ori,is.numeric))
db_new<-db_ori[,numericalVariablesIndex]
db_new$Category<-db_ori$Category
db_new$Content.Rating<-db_ori$Content.Rating
res.pca <- PCA(db_new,quali.sup = 8:9, graph=FALSE)

res.pca$quali


fviz_pca_ind(res.pca, habillage = 8,select.ind=list(cos2 = 1000),
             addEllipses =TRUE, ellipse.type = "confidence",
             palette = "jco", repel = TRUE,mean.point = FALSE) 


fviz_pca_var(res.pca, habillage = 8,col.var = "cos2",
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"), 
             repel = TRUE # Avoid text overlapping
             )

fviz_pca_ind(res.pca, col.ind = "contrib", select.ind = list(contrib = 100),
             label="none", habillage=db_ori$Content.Rating,
     addEllipses=TRUE, ellipse.level=0.65, palette = "Dark2")
```



