from rdflib import Graph, Namespace, RDF, RDFS, Literal

# Create a namespace
ns = Namespace('http://example.org/')

# Create a graph
g = Graph()

# Define the classes
g.add((ns.Person, RDF.type, RDFS.Class))
g.add((ns.Author, RDF.type, RDFS.Class))
g.add((ns.Reviewer, RDF.type, RDFS.Class))
g.add((ns.Handler, RDF.type, RDFS.Class))
g.add((ns.Chair, RDF.type, RDFS.Class))
g.add((ns.Editor, RDF.type, RDFS.Class))
g.add((ns.Paper, RDF.type, RDFS.Class))
g.add((ns.Publication, RDF.type, RDFS.Class))
g.add((ns.Submission, RDF.type, RDFS.Class))
g.add((ns.Revision, RDF.type, RDFS.Class))
g.add((ns.Conference, RDF.type, RDFS.Class))
g.add((ns.Journal, RDF.type, RDFS.Class))
g.add((ns.Venue, RDF.type, RDFS.Class))
g.add((ns.Full_paper, RDF.type, RDFS.Class))
g.add((ns.Short_paper, RDF.type, RDFS.Class))
g.add((ns.Demo_paper, RDF.type, RDFS.Class))
g.add((ns.Poster_paper, RDF.type, RDFS.Class))
g.add((ns.Workshop, RDF.type, RDFS.Class))
g.add((ns.Symposium, RDF.type, RDFS.Class))
g.add((ns.Expert_group, RDF.type, RDFS.Class))
g.add((ns.Regular_conference, RDF.type, RDFS.Class))
g.add((ns.Proceeding, RDF.type, RDFS.Class))
g.add((ns.Volume, RDF.type, RDFS.Class))
g.add((ns.Area, RDF.type, RDFS.Class))

# Define the subclasses
g.add((ns.Author, RDFS.subClassOf, ns.Person))
g.add((ns.Reviewer, RDFS.subClassOf, ns.Person))
g.add((ns.Handler, RDFS.subClassOf, ns.Person))
g.add((ns.Chair, RDFS.subClassOf, ns.Handler))
g.add((ns.Editor, RDFS.subClassOf, ns.Handler))
g.add((ns.Conference, RDFS.subClassOf, ns.Venue))
g.add((ns.Journal, RDFS.subClassOf, ns.Venue))
g.add((ns.Full_paper, RDFS.subClassOf, ns.Paper))
g.add((ns.Short_paper, RDFS.subClassOf, ns.Paper))
g.add((ns.Demo_paper, RDFS.subClassOf, ns.Paper))
g.add((ns.Poster_paper, RDFS.subClassOf, ns.Paper))
g.add((ns.Workshop, RDFS.subClassOf, ns.Conference))
g.add((ns.Symposium, RDFS.subClassOf, ns.Conference))
g.add((ns.Expert_group, RDFS.subClassOf, ns.Conference))
g.add((ns.Regular_conference, RDFS.subClassOf, ns.Conference))
g.add((ns.Proceeding, RDFS.subClassOf, ns.Publication))
g.add((ns.Volume, RDFS.subClassOf, ns.Publication))

# Define the properties
g.add((ns.writes, RDF.type, RDF.Property))
g.add((ns.submittedTo, RDF.type, RDF.Property))
g.add((ns.presentedAt, RDF.type, RDF.Property))
g.add((ns.handles, RDF.type, RDF.Property))
g.add((ns.accepted, RDF.type, RDF.Property))
g.add((ns.goesThrough, RDF.type, RDF.Property))
g.add((ns.does, RDF.type, RDF.Property))
g.add((ns.decision, RDF.type, RDF.Property))
g.add((ns.reviewText, RDF.type, RDF.Property))
g.add((ns.includedIn, RDF.type, RDF.Property))
g.add((ns.paperRelatedTo, RDF.type, RDF.Property))
g.add((ns.venueRelatedTo, RDF.type, RDF.Property))
g.add((ns.venueName, RDF.type, RDF.Property))
g.add((ns.publishes, RDF.type, RDF.Property))
g.add((ns.publicationYear, RDF.type, RDF.Property))
g.add((ns.volumeNumber, RDF.type, RDF.Property))
g.add((ns.topic, RDF.type, RDF.Property))
g.add((ns.personName, RDF.type, RDF.Property))
g.add((ns.paperTitle, RDF.type, RDF.Property))

# Define the domain and range of the properties
g.add((ns.writes, RDFS.domain, ns.Author))
g.add((ns.writes, RDFS.range, ns.Paper))
g.add((ns.submittedTo, RDFS.domain, ns.Paper))
g.add((ns.submittedTo, RDFS.range, ns.Submission))
g.add((ns.presentedAt, RDFS.domain, ns.Submission))
g.add((ns.presentedAt, RDFS.range, ns.Venue))
g.add((ns.handles, RDFS.domain, ns.Handler))
g.add((ns.handles, RDFS.range, ns.Submission))
g.add((ns.accepted, RDFS.domain, ns.Submission))
g.add((ns.accepted, RDFS.range, RDFS.Literal))
g.add((ns.goesThrough, RDFS.domain, ns.Submission))
g.add((ns.goesThrough, RDFS.range, ns.Revision))
g.add((ns.does, RDFS.domain, ns.Reviewer))
g.add((ns.does, RDFS.range, ns.Revision))
g.add((ns.decision, RDFS.domain, ns.Revision))
g.add((ns.decision, RDFS.range, RDFS.Literal))
g.add((ns.reviewText, RDFS.domain, ns.Revision))
g.add((ns.reviewText, RDFS.range, RDFS.Literal))
g.add((ns.includedIn, RDFS.domain, ns.Paper))
g.add((ns.includedIn, RDFS.range, ns.Publication))
g.add((ns.paperRelatedTo, RDFS.domain, ns.Paper))
g.add((ns.paperRelatedTo, RDFS.range, ns.Area))
g.add((ns.venueRelatedTo, RDFS.domain, ns.Venue))
g.add((ns.venueRelatedTo, RDFS.range, ns.Area))
g.add((ns.venueName, RDFS.domain, ns.Venue))
g.add((ns.venueName, RDFS.range, RDFS.Literal))
g.add((ns.publishes, RDFS.domain, ns.Venue))
g.add((ns.publishes, RDFS.range, ns.Publication))
g.add((ns.publicationYear, RDFS.domain, ns.Publication))
g.add((ns.publicationYear, RDFS.range, RDFS.Literal))
g.add((ns.volumeNumber, RDFS.domain, ns.Volume))
g.add((ns.volumeNumber, RDFS.range, RDFS.Literal))
g.add((ns.topic, RDFS.domain, ns.Area))
g.add((ns.topic, RDFS.range, RDFS.Literal))
g.add((ns.personName, RDFS.domain, ns.Person))
g.add((ns.personName, RDFS.range, RDFS.Literal))
g.add((ns.paperTitle, RDFS.domain, ns.Paper))
g.add((ns.paperTitle, RDFS.range, RDFS.Literal))

g.serialize('tbox.ttl', format="turtle")
