---
output: html_document
editor_options: 
  chunk_output_type: console
---


# Load data

```{r}
rm(list=ls())

library(AER)
library(car)
library(FactoMineR)
data("SwissLabor")
```

# Take a look

```{r}
df<-SwissLabor
head(df)
summary(df)
```

October 5th, 2022

```{r}
df$participation<-factor(df$participation,labels=paste("f.Par",sep="-",levels(df$participation)))
df$foreign<-factor(df$foreign,labels=paste("f.For",sep="-",levels(df$foreign)))
summary(df)


```


# Examples for Imputation and Outlier detection 

```{r}
library(mvoutlier)
names(df)
vout<-aq.plot(df[,2:4], delta=qchisq(0.975,3),alpha=0.025)
summary(df)


library(chemometrics)
dis <- Moutlier(SwissLabor[,2:4], quantile = 0.975)
dis$cutoff
str(dis)
par(mfrow=c(1,1))
plot(dis$md,dis$rd, type="n")
text(dis$md,dis$rd,labels=rownames(SwissLabor[,2:4]))
abline(h=sqrt(qchisq(0.995, ncol(SwissLabor[,2:4]))),col="red",lwd=2)
abline(v=sqrt(qchisq(0.995, ncol(SwissLabor[,2:4]))),col="red",lwd=2)
```

Profiling

```{r}
# Target participation - Factor

# Global association  participation and the rest of factors

# Global association  participation and the rest of   numeric vars
oneway.test(df$income~df$participation)  # H0: mean income f.Par-Yes = mean income f.Par-NO pvalue=P(H0)= 2 e-7 << 0.05 -> H0 Rejected - Income and Participation association proof

prop.table(table(df$participation))
prop.table(table(df$foreign))
table( df$foreign,df$participation ) 

res.cat<-catdes(df,1)
str(res.cat)
res.cat$quanti.var  # Global association target is factor and explanatory variables numeric
res.cat$quanti # Especific association: target factor and numeric variables
res.cat$test.chi2 # Global association target is factor and explanatory factors
res.cat$category

indtest<-chisq.test(table(df$foreign,df$participation));indtest$expected

names(df)
res.con<-condes(df,2) # Target income 
res.con$quanti  # Global Association Target income and explanatory covariates
res.con$quali # Global Association Target income and explanatory factors
res.con$category

```

**Discuss Examples in third laboratory class for Session 1**