---
title: "Session12-12-22"
output: html_document
date: '2022-12-12'
---

```{r}
load("Womenlf.RData")
summary(womenlf)
str(womenlf)
df <- womenlf

womenlf$bwork<-ifelse(womenlf$work=="not_work",0,1)
womenlf$bwork<-factor(womenlf$bwork,labels=c("not_work","work"))
```

#Binary model ML1
```{r}
hm1m0 <- glm( bwork ~ 1, family="binomial",data=womenlf)
#Too big model
hm1m9 <- glm( bwork ~ sons*income + sons *region, family="binomial",data=womenlf)
step(hm1m9)
hm1m3 <- glm( bwork ~ sons + income, family="binomial",data=womenlf)
summary(hm1m3)

coef(hm1m3)
exp(coef(hm1m3))
100*(1-exp(-1.57564843))

#odds(sons~present) = 0.2 odds(sons~absent) or odds are reduced by 80% when sons-present all else 
# being equal (ceteris paribus)

#Interpretation in he probability scale
propsample <- prop.table(table(womenlf$bwork)); propsample
0.5893536 * 0.4106464 * coef(hm1m3)[2] 

# having sons (sons present) represent a decrease of 0.38 units in the absolute probability ( en el que esta haciendo la profe lo de arriba da -0.38 ver que tengo mal porque me da -0.26 y dice sonspresent en el de la profe no sons.L )


#income
# odds scale interpretation?
coef(hm1m3)[3]
exp(coef(hm1m3)[3])
100*(1-exp(coef(hm1m3)[3]))
# for each additional unit in income odds decrease by 4%
0.5893536 * 0.4106464 * coef(hm1m3)[3] 

```

#Polytomous factor

## nominal proposal
```{r}
library(nnet)
mm0 <-multinom(  work~1, data=womenlf,weight=ones ) # null model
summary(mm0)
mm3 <-multinom(  work~sons+income, data=womenlf,weight=ones )
summary(mm3)

coef(mm3)
exp(coef(mm3))
#odds scale PT (partial time)  vs NW (no work)
100*(exp(coef(mm3)[1,2:3])-1)

#odds scale FT (full time)  vs NW
exp(coef(mm3)[2,2:3])
100*(1- exp(coef(mm3)[1,2:3]))
```


#
```{r}
# Interpret sons absent and income on the mean

mean(womenlf$income)

mm3c <-multinom( work~ sons+I(income - mean(womenlf$income)), data=womenlf,weight=ones )
summary(mm3c)

lopPT <- coef(mm3c)[1,1];lopPT
lopFT <- coef(mm3c)[2,1];lopFT
opPT <- exp(lopPT);opPT
opFT <- exp(lopFT);opFT
pNW <- (1/(1+opPT+opFT));pNW

predict(mm3c, newdata=data.frame(sons="absent",income=14.76),type="probs")
predict(mm3c, newdata=data.frame(sons="absent",income=14.76),type="class")

## Accuracy

tt<-table(predict(mm3),womenlf$work);tt
100*sum(diag(tt))/sum(tt)
```

## Ordinal
```{r}
library(MASS)
om0 <-polr( work~1, data=womenlf,weight=ones )
om9 <-polr( work~sons*income + region, data=womenlf,weight=ones )
om3 <-step(om9)
summary(om0)  ## 
summary(om3)

predict()

#predict probabilities sons absent and income on the mean. Use the trick om3c
om3c <-polr( work~ sons+I(income - mean(womenlf$income)), data=womenlf,weight=ones )
summary(om3c)

om3c$zeta

clogogg1 <- om3c$zeta[1]; clogogg1 #linea predictors!
clogogg2 <- om3c$zeta[2]; clogogg2

gam1 <- exp(clogogg1)/ (1-exp(clogogg1)); gam1
gam2 <- exp(clogogg2)/ (1-exp(clogogg2)); gam2

pNW <- gam1; pNW
pPT <- gam2 - gam1; pPT
pFT <- 1-gam2; pFT



```





