ALTER TABLE AIRCRAFTDIMENSION SHRINK SPACE;
ALTER TABLE PEOPLEDIMENSION SHRINK SPACE;
ALTER TABLE TEMPORALDIMENSION SHRINK SPACE;
ALTER TABLE MONTHS SHRINK SPACE;
ALTER TABLE AIRCRAFTUTILIZATION SHRINK SPACE;
ALTER TABLE LOGBOOKREPORTING SHRINK SPACE;

-- CREATE UNIQUE CONSTRAINT
ALTER TABLE AIRCRAFTDIMENSION ADD CONSTRAINT UNIQUE_AIRCDIM_ID UNIQUE (ID) USING INDEX PCTFREE 33;
CREATE BITMAP INDEX MODEL_AIRCRAFTUTIL
ON AIRCRAFTUTILIZATION( d.MODEL )
FROM AIRCRAFTUTILIZATION f, AIRCRAFTDIMENSION d
WHERE f.AIRCRAFTID = d.ID PCTFREE 0;


CREATE BITMAP INDEX IND_AIRCRAFTID ON AIRCRAFTUTILIZATION(AIRCRAFTID) PCTFREE 0;


CREATE BITMAP INDEX MODEL_LOGBOOKS
ON LOGBOOKREPORTING( d.MODEL )
FROM LOGBOOKREPORTING f, AIRCRAFTDIMENSION d
WHERE f.AIRCRAFTID = d.ID PCTFREE 0;

-- CREATE UNIQUE CONSTRAINT
ALTER TABLE PeopleDimension ADD CONSTRAINT UNIQUE_PEOPLEDIM_ID UNIQUE (ID) USING INDEX PCTFREE 33;
CREATE BITMAP INDEX PEOPLE_LOGBOOKS
ON LOGBOOKREPORTING( d.airport )
FROM LOGBOOKREPORTING f, PeopleDimension d
WHERE f.PERSONID = d.ID PCTFREE 0;


-- update statistics

DECLARE
esquema VARCHAR2(100);
CURSOR c IS SELECT TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME NOT LIKE 'SHADOW_%';
BEGIN
SELECT '"'||sys_context('USERENV', 'CURRENT_SCHEMA')||'"' INTO esquema FROM dual;
FOR taula IN c LOOP
  DBMS_STATS.GATHER_TABLE_STATS( 
    ownname => esquema, 
    tabname => taula.table_name, 
    estimate_percent => NULL,
    method_opt =>'FOR ALL COLUMNS SIZE REPEAT',
    granularity => 'GLOBAL',
    cascade => TRUE
    );
  END LOOP;
END;


-- check occupied space
SELECT SUM(blocks) FROM USER_TS_QUOTAS;


-- BEFORE USING INDEXES COSTS
-- KPI 1: 653
-- KPI 2: 652
-- KPI 3: 1922
-- KPI 4: 1902

-- COST WITH INDEXES
-- KPI 1: 170
-- KPI 2: 141
-- KPI 3: 543
-- KPI 4: 787